---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Pull image
      docker_image:
        name: aasmaan1/calculator:latest
        source: pull

    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Stop and remove container
      shell: |
        docker stop Calculator
        docker rm Calculator
    - name: Running container
      shell: docker run -it -d --name Calculator aasmaan1/calculator
#heheklkm
#some commentkjbkjwjn
